# Generated by Django 3.2.12 on 2023-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='images',
            field=models.ImageField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
