# Generated by Django 3.2.12 on 2023-08-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.location'),
            preserve_default=False,
        ),
    ]
